CREATE DATABASE PROJECTS;
USE PROJECTS;
SELECT * FROM indian_gdp2;

-- 1. WHICH YEAR HAS THE LOWEST PER CAPITA INCOME
SELECT `year`, Per_Capita_in_rupees AS LOWEST_PER_CAPITA
FROM indian_gdp2
WHERE Per_Capita_in_rupees=(SELECT min(Per_Capita_in_rupees)FROM indian_gdp2) LIMIT 1;

-- 2. WHICH YEAR HAS THE HIGHEST PER CAPITA INCOME
SELECT `year`, Per_Capita_in_rupees AS HIGHEST_PER_CAPITA
FROM indian_gdp2
WHERE Per_Capita_in_rupees=(SELECT max(Per_Capita_in_rupees)FROM indian_gdp2);

-- 3. WHICH YEAR HAS THE LOWEST GDP
SELECT `year`, GDP_in_Billion$ AS LOWEST_GDP_IN_BILLION_$
FROM indian_gdp2
WHERE GDP_in_Billion$ =(SELECT min(GDP_in_Billion$)FROM indian_gdp2) LIMIT 1;

-- 4. WHICH YEAR HAS THE HIGHEST GDP INCOME
SELECT `year`, GDP_in_Billion$ AS HIGHEST_GDP_IN_BILLION_$
FROM indian_gdp2
WHERE GDP_in_Billion$=(SELECT MAX(GDP_in_Billion$) FROM indian_gdp2);

-- 5. WHICH YEAR HAS THE HIGHEST PERCENTAGE GROWTH IN GDP
SELECT `year`, growth_percentage AS HIGHEST_PERCENTAGE_GROWTH_IN_ONE_YEAR
FROM indian_gdp2
WHERE growth_percentage=(SELECT MAX(growth_percentage) FROM indian_gdp2);

-- 6. TOP 3 YEARS WITH HIGHEST GDP
SELECT `year`, GDP_in_Billion$ AS TOP_3_YEARS_WITH_HIGHEST_GDP_IN_BILLION
FROM indian_gdp2
ORDER BY GDP_in_Billion$ DESC LIMIT 3;

-- 7. TOP 3 YEARS WITH HIGHEST PER CAPITA INCOME
SELECT `year`, Per_Capita_in_rupees AS TOP_3_YEARS_WITH_HIGHEST_PER_CAPITA
FROM indian_gdp2
ORDER BY GDP_in_Billion$ DESC LIMIT 3;

-- 8. COUNT OF YEARS WHEN GROWTH WAS IN NEGATIVE
SELECT COUNT(Growth_percentage) AS NUMBER_OF_YEARS_WITH_NEGATIVE_GROWTH
FROM indian_gdp2
WHERE Growth_percentage < 0;

-- 9. YEARS WHEN GROWTH WAS IN NEGATIVE
SELECT `year`, Growth_percentage AS NEGATIVE_GROWTH_YEARS
FROM indian_gdp2
WHERE Growth_percentage < 0
ORDER BY Growth_percentage DESC;

-- 10. TOP 3 YEARS WITH LOWEST GDP
SELECT `year`, GDP_in_Billion$ AS 3_LOWEST_GDP_IN_BILLION_$
FROM indian_gdp2
ORDER BY GDP_in_Billion$ ASC LIMIT 1,3;

-- 11. TOP 3 YEARS WITH LOWEST PER CAPITA INCOME
SELECT `year`, Per_Capita_in_rupees AS 3_LOWEST_PER_CAPITA_IN_RS
FROM indian_gdp2
ORDER BY Per_Capita_in_rupees ASC LIMIT 1,3;

-- 12.YEARS WHEN GDP WAS MORE THAN 1 TRILLION DOLLARS
SELECT `year`, GDP_in_Billion$ AS GDP_MORE_THAN_1_TRILLION
FROM indian_gdp2
WHERE GDP_in_Billion$>=1000 ORDER BY GDP_in_Billion$ ASC;

-- 13. COUNT OF YEARS WHEN GDP WAS MORE THAN 1 TRILLION DOLLARS
SELECT COUNT(GDP_in_Billion$) AS NO_OF_YEARS_GDP_MORE_THAN_1_TRILLION
FROM indian_gdp2
WHERE GDP_in_Billion$ > 1000;

-- 14. GDP IN THE BEGGINING 5 YEARS
SELECT * FROM indian_gdp2
ORDER BY Year ASC LIMIT 1,5;

-- 15. GROWTH PERCENTAGE DECADE WISE
SELECT 
  FLOOR(year / 10) * 10 AS Decade,
  AVG(growth_percentage) AS Avg_Growth_Percentage
FROM indian_gdp2
GROUP BY Decade;
